// ---------------------------------------------------------------------------
// postbuild.cjs — runs after `electron-vite build`.
//
// Why this exists: electron-vite's externalizeDepsPlugin hoists every
// external `require(...)` call (playwright, electron, etc.) to the very top
// of the bundled out/main/index.js, ahead of any of our own code — including
// code that sets PLAYWRIGHT_BROWSERS_PATH before Playwright resolves its
// browser registry. Setting the env var *inside* the bundle is therefore too
// late in a packaged build.
//
// Fix: rename the real bundle to app.js, then write a tiny unbundled shim as
// index.js (Electron's `main` entry) that sets the env var and requires the
// real bundle. This shim is never touched by Rollup, so ordering is exact.
// ---------------------------------------------------------------------------
const fs = require('fs')
const path = require('path')

const mainDir = path.join(__dirname, '..', 'out', 'main')
const realBundle = path.join(mainDir, 'index.js')
const renamedBundle = path.join(mainDir, 'app.js')

if (!fs.existsSync(realBundle)) {
  console.error('[postbuild] out/main/index.js not found — did the build fail?')
  process.exit(1)
}

// splash.html is a plain static file, not a bundled entry point — electron-
// vite's main build never touches/copies it, so it must be placed into
// out/main/ manually here (same directory main/index.ts's splashWindow
// loads it from via join(__dirname, 'splash.html')).
const splashSrc = path.join(__dirname, '..', 'src', 'main', 'splash.html')
const splashDest = path.join(mainDir, 'splash.html')
if (fs.existsSync(splashSrc)) {
  fs.copyFileSync(splashSrc, splashDest)
  console.log('[postbuild] copied splash.html to out/main/splash.html')
} else {
  console.warn('[postbuild] src/main/splash.html not found — skipping splash screen asset copy')
}

fs.renameSync(realBundle, renamedBundle)

const shim = `"use strict";
// Auto-generated by scripts/postbuild.cjs — do not edit by hand.
// Sets PLAYWRIGHT_BROWSERS_PATH before requiring the real bundle (app.js),
// which is the earliest point at which we can influence Playwright's browser
// registry resolution in a packaged build (see postbuild.cjs for why).
//
// NOTE: use property access (electron.app), not destructuring, and guard
// with optional chaining. Destructuring \`app\` at the very top of the main
// entry module can observe electron's CJS export binding before Electron
// finishes wiring it, yielding undefined here even though the exact same
// require() a few lines later in app.js resolves fine.
const electron = require('electron');
const path = require('path');
const fs = require('fs');

if (electron && electron.app && electron.app.isPackaged) {
  const bundled = path.join(process.resourcesPath, 'ms-playwright');
  if (fs.existsSync(bundled)) {
    process.env.PLAYWRIGHT_BROWSERS_PATH = bundled;
  }
}

require('./app.js');
`

fs.writeFileSync(realBundle, shim, 'utf8')
console.log('[postbuild] wrote PLAYWRIGHT_BROWSERS_PATH shim to out/main/index.js (real bundle: app.js)')
